#!/usr/bin/env python3
"""Regenerate examples/demo-site-output.md: real output of check_ai_readiness.py on the fictional demo site.

Usage:
    python3 tools/make_demo_report.py          # rewrite examples/demo-site-output.md
    python3 tools/make_demo_report.py --check  # exit 1 if the committed file is out of date

The file is derived from a live run, never edited by hand; tests/test_demo.py fails if it drifts.
"""
import importlib.util
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "examples", "demo-site-output.md")
PATHS = ["/pricing", "/features", "/blog/crm-for-agencies"]
AGENTS = [("browser", "Default fetch"), ("listed crawler (GPTBot)", "GPTBot"), ("user-fetch (Claude-User)", "Claude-User"),
          ("user-fetch (ChatGPT-User)", "ChatGPT-User"), ("search crawler (Googlebot)", "Googlebot"),
          ("search crawler (Bingbot)", "Bingbot")]


def _load(name, relpath):
    spec = importlib.util.spec_from_file_location(name, os.path.join(ROOT, relpath))
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def words_table(findings):
    rows = []
    for f in findings:
        if not f["check"].startswith("render by agent: /"):
            continue
        cells = []
        for key, _ in AGENTS:
            m = re.search(re.escape(key) + r": HTTP \d+, (\d+) words", f["detail"])
            cells.append(f"{int(m.group(1)):,}" if m else "?")
        rows.append(f"| `{f['check'].split(': ', 1)[1]}` | " + " | ".join(cells) + f" | {f['status']} |")
    head = ["| Page | " + " | ".join(label for _, label in AGENTS) + " | Verdict |", "|---|" + "---|" * (len(AGENTS) + 1)]
    return "\n".join(head + rows), rows


def build(port=0):
    """Run the checker against the demo site and return the markdown document (always shown on the documented port)."""
    demo = _load("demo_site", os.path.join("examples", "demo_site.py"))
    ck = _load("check_ai_readiness", os.path.join("geo-visibility", "scripts", "check_ai_readiness.py"))
    server = demo.serve_in_background(port)
    actual = server.server_address[1]
    try:
        res = ck.check(f"http://127.0.0.1:{actual}", PATHS)
    finally:
        server.shutdown()
        server.server_close()
    output = ck.to_markdown(res, issues_only=True).replace(f"127.0.0.1:{actual}", f"127.0.0.1:{demo.PORT}")
    table, _ = words_table(res["findings"])
    paths = " ".join(PATHS)
    return f"""# Demo: the readiness checker on a deliberately flawed site

> **Real, unedited output.** Everything between the rules below is what `check_ai_readiness.py` prints when pointed at [`demo_site.py`](demo_site.py), a small fictional site ("Meridian CRM") that ships in this repo with flaws planted on purpose. No real company's site is involved, and you can reproduce it in two commands:
>
> ```bash
> python3 examples/demo_site.py &
> python3 geo-visibility/scripts/check_ai_readiness.py http://127.0.0.1:{demo.PORT} --paths {paths} --issues-only
> ```
>
> This file is generated by `tools/make_demo_report.py` and a test fails if it drifts from what the tool really prints.

---

{output}

---

## Words each agent received (from the same run's JSON output)

The checker fetches every `--paths` page as a browser, as GPTBot, as two user-fetch agents, as Googlebot and as Bingbot, using realistic user-agent strings, and compares what comes back without running JavaScript.

{table}

## What was planted, and where the checker found it

| Planted flaw | Where it shows up |
|---|---|
| `robots.txt` disallows `Claude-SearchBot` | Must fix #1. (`GPTBot` is disallowed too, but a training opt-out is a choice, so it appears under Other notes as `info`.) |
| A bot rule refuses `PerplexityBot` with HTTP 403 | Must fix #2 |
| `/pricing` is an empty JavaScript app shell for every agent | Must fix #3, and 0 words in every column above |
| The homepage has no JSON-LD | Must fix #4 and #8 |
| `/blog/crm-for-agencies` is a full page for Googlebot but a shell for Bingbot | Must fix #5, and the 0 in the Bingbot column |
| The homepage sets `nosnippet`, as an SEO plugin might | Must fix #6 |
| Every sitemap entry has the same `lastmod` | Must fix #7 |
| `/features` is a shell for a default fetch but full HTML for crawlers | Not a problem: the checker credits it as dynamic rendering by user agent (the pass row hidden by `--issues-only`; note the Default fetch column) |
| No Bing Webmaster Tools tag, no `llms.txt` | Worth checking |
"""


def main(argv):
    doc = build()
    if "--check" in argv:
        current = ""
        if os.path.exists(OUT):
            with open(OUT, encoding="utf-8") as fh:
                current = fh.read()
        if current != doc:
            print("examples/demo-site-output.md is out of date: run python3 tools/make_demo_report.py", file=sys.stderr)
            return 1
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(doc)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
